In [4]:
import numpy as np
a = np.zeros(5)
a.ndim # its 1 dimantion array

1

In [5]:
a # its a float

array([0., 0., 0., 0., 0.])

In [8]:
a = np.zeros(10, dtype=int) # float to int
a
a.ndim

1

In [12]:
b = np.zeros((3,4))
b.ndim

2

In [13]:
np.ones(5) # all values are one


array([1., 1., 1., 1., 1.])

In [15]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [16]:
arr = np.zeros((3,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
arr.ndim

3

In [21]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
a = arr+5
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [26]:
b= a*2
b

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.empty(3)

array([1., 1., 1.])

In [35]:
import random
random.choice((1,2,3,4))


3

In [36]:
random.choice("Sneha")

'n'

In [37]:
random.randrange(1, 10)


6

In [38]:
random.random()

0.17075139281955964

In [39]:
lis = [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [44]:
random.shuffle(lis)
lis

[4, 3, 1, 2, 5]

In [ ]:
# random number concept in numpy


In [45]:
np.array([])

array([], dtype=float64)

In [46]:
np.random.random_sample()

0.36159400894140903

In [48]:
 np.random.random_sample((5,)) # 1 dim array of random numbers

array([0.70949956, 0.4504167 , 0.85604852, 0.39645826, 0.34424947])

In [49]:
np.random.rand(1)

array([0.78785645])

In [50]:
np.random.rand(2,3)

array([[0.00691618, 0.93711095, 0.68412585],
       [0.19770034, 0.00328338, 0.00583484]])

In [51]:
np.random.randn(2,3)

array([[-0.54976208,  0.69226544, -0.63581467],
       [ 1.41688324,  0.58512501,  1.15207335]])

In [4]:
import numpy as np
arr = np.random.randint(1,5, size = (3,4))
# arr.shape

(3, 4)

In [5]:
arr.reshape(2,6)

array([[4, 1, 1, 1, 1, 3],
       [4, 3, 2, 2, 3, 2]])

In [7]:
arr1 = np.random.randint(1,10,(5,6))
arr1

array([[6, 4, 7, 3, 2, 5],
       [1, 2, 1, 6, 8, 1],
       [7, 3, 3, 1, 7, 7],
       [3, 7, 5, 5, 8, 5],
       [7, 7, 2, 6, 8, 6]])

In [ ]:
# to access elements in array

In [9]:
arr1[1]

array([1, 2, 1, 6, 8, 1])

In [10]:
arr1[3][1]

np.int64(7)

In [ ]:
# from 0th row and second row

In [15]:
arr1[0:3,[0,2]]

array([[6, 7],
       [1, 1],
       [7, 3]])

In [16]:
# slicing on both rows and columns togather
arr1

array([[6, 4, 7, 3, 2, 5],
       [1, 2, 1, 6, 8, 1],
       [7, 3, 3, 1, 7, 7],
       [3, 7, 5, 5, 8, 5],
       [7, 7, 2, 6, 8, 6]])

In [20]:
arr1[0:3, 1:3]

array([[4, 7],
       [2, 1],
       [3, 3]])

In [21]:
arr[0:3, [0,1]]

array([[4, 1],
       [1, 3],
       [2, 2]])

In [23]:
arr1[0,[1,3]]

array([4, 3])

In [ ]:
arr1[2:4, [0,3]] # 2nd and 3rd row and also 0 and 3rd column

In [24]:
arr1[2:5]

array([[7, 3, 3, 1, 7, 7],
       [3, 7, 5, 5, 8, 5],
       [7, 7, 2, 6, 8, 6]])

In [27]:
arr1[2:5, 0:2]

array([[7, 3],
       [3, 7],
       [7, 7]])

In [ ]:
# Mathematical operation on two arrays

In [32]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [43]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [44]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
arr1+arr2 # indexwise element

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [46]:
arr1, arr2

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]))

In [47]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# matrix multiplication >> matrix is a specialised to 2-d array
#  matrix multiplication  is different from indexwise multiplication

In [48]:
arr1 @ arr2

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [49]:
np.dot(arr1, arr2)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])